# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/alejandroe/Desktop/project_1/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/alejandroe/Desktop/project_1/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  C:/Users/alejandroe/Desktop/project_1/project_1/project_1.srcs/sources_1/new/fullAdder.v
  C:/Users/alejandroe/Desktop/project_1/project_1/project_1.srcs/sources_1/new/halfAdder.v
  C:/Users/alejandroe/Desktop/project_1/project_1/project_1.srcs/sources_1/new/adder.v
  C:/Users/alejandroe/Desktop/project_1/project_1/project_1.srcs/sources_1/new/multiplier.v
  C:/Users/alejandroe/Desktop/project_1/project_1/project_1.srcs/sources_1/new/subtractor.v
  C:/Users/alejandroe/Desktop/project_1/project_1/project_1.srcs/sources_1/new/ALUcontrol.v
  C:/Users/alejandroe/Desktop/project_1/project_1/project_1.srcs/sources_1/new/control.v
  C:/Users/alejandroe/Desktop/project_1/project_1/project_1.srcs/sources_1/new/ALU.v
  C:/Users/alejandroe/Desktop/project_1/project_1/project_1.srcs/sources_1/new/MIPS_instr_mem.v
  C:/Users/alejandroe/Desktop/project_1/project_1/project_1.srcs/sources_1/new/MIPS_registerfile.v
  C:/Users/alejandroe/Desktop/project_1/project_1/project_1.srcs/sources_1/new/memory.v
  C:/Users/alejandroe/Desktop/project_1/project_1/project_1.srcs/sources_1/new/mux2_1.v
  C:/Users/alejandroe/Desktop/project_1/project_1/project_1.srcs/sources_1/new/signExt.v
  C:/Users/alejandroe/Desktop/project_1/project_1/project_1.srcs/sources_1/new/top.v
}
read_xdc C:/Users/alejandroe/Downloads/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/Users/alejandroe/Downloads/Nexys4DDR_Master.xdc]

synth_design -top top -part xc7a100tcsg324-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
